<?php
/**
 * Implements hook_preprocess_page().
 */
function test_theme_preprocess_page(&$variables) {
  // Pass custom footer text to the template.
  $variables['custom_footer_text'] = theme_get_setting('custom_footer_text');
  // Pass custom background color to the template.
  $variables['custom_bg_color'] = theme_get_setting('custom_bg_color');
  // Pass dark mode setting to the template.
  $variables['enable_dark_mode'] = theme_get_setting('enable_dark_mode');

  // Pass site name to the template.
  $variables['custom_site_name'] = theme_get_setting('custom_site_name');
  // Pass a custom message to the template.
  $variables['welcome_message'] = "Welcome to " . $variables['custom_site_name'] . "!";
}


// If the page is /featured then add custom suggestions
function test_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Get the current route name
  $route_name = \Drupal::routeMatch()->getRouteName();

  // Check if we are on the "Featured Page" (Adjust the path accordingly)
  if ($route_name === 'view.featured_recipes_grid.page_1') {
    $suggestions[] = 'page__featured__through__preprocess__function';
  }
}


/**
 * Implements hook_theme_suggestions_HOOK_alter() for theme debug.
 */
// function test_theme_preprocess_page(array &$variables) {
//   // Check if the site is in a development environment
// if (\Drupal::currentUser()->isAuthenticated()) {
//   // Enable Twig development mode for logged-in users
//   $config['system.twig']['development_mode'] = TRUE;
// }
// else {
//   // Disable Twig development mode for non-logged-in users
//   $config['system.twig']['development_mode'] = FALSE;
// }

// }
